name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: プルリクエストの情報を表示
        run: |
          echo "プルリクエストのブランチ名: ${{ github.head_ref }}"
          echo "プルリクエストの番号: ${{ github.event.pull_request.number }}"
          echo "プルリクエストの作成者: ${{ github.event.pull_request.user.login }}"
      - name: チェックアウトする
        uses: actions/checkout@v4
        id: checkout
      - name: actions/checkoutのステータスを表示
        run: echo "${{ steps.checkout.conclusion }}"
      - name: Goの環境をセットアップする
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: フォーマットを実行する
        run: test -z $(gofmt -l .)
      - name: 静的解析を実行する
        run: go vet ./...
      - name: テストを実行する
        run: go test
      - name: ビルドを実行する
        run: go build .
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ビルド処理
        run: touch /output/build.txt
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /output/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: 成果物のダウンロード
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ../../output/
      - name: GitHub Releaseへのデプロイ
        run: gh release upload v1.0.0 outpuut/artifact.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}